spring:
      datasource:
                url: jdbc:postgresql://localhost:5432/bot
                driver-class-name: org.postgresql.Driver
                username: postgres
                password: 1234567890
      jpa:
          hibernate:
                  ddl-auto: update

server:
      port: 1208

interval-in-cron: 0 0 9 * * *

telegram-bot:
            name: changeMe
            token: changeMe
